#### general settings
name: D2SR_setting2_stage3_x4_dcls
use_tb_logger: true
model: blind
distortion: sr
scale: 4
gpu_ids: [0]
cal_ker: false
net2_opt: /userHome/guest/wangjia/blindsr/DDL-BSR/codes/config/DDLBSR/options/train/danv1_setting2_x4.yml

#/userHome/guest/wangjia/blindsr/DCLS-SR/codes/config/DCLS/options/setting2/train/train_setting2_x4.yml

# train
degradation:
  random_kernel: true
  ksize: 31
  code_length: 10
  sig_min: 0.6
  sig_max: 5
  rate_iso: 0
  random_disturb: true
  noise: true
  noise_high: 0.05882
pca_matrix_path: /userHome/guest/wangjia/blindsr/D2SR/pca_matrix/pca_aniso_matrix_x4.pth


#### datasets
datasets:
  train:
    name: DIV2K+Flickr2K
    mode: GT
    dataroot_GT: /data/wangjia/BSR/train/DF2K/HR
    dataroot_LQ: ~

    use_shuffle: true
    n_workers: 8
    batch_size: 2
    GT_size: 256
    LR_size: 64
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Set5
    mode: LQGT
    dataroot_GT: /data/wangjia/BSR/test/Setting2/Set5/HR/x4
    dataroot_LQ: /data/wangjia/BSR/test/Setting2/Set5/LRblur/x4


#### network structures
network_G:
  which_model_G: D2SR_s3
  setting:
    scale: 4
    ksize: 31


#### path
path:
  pretrain_model_G: ~
  pretrain_model_K: ~ #/userHome/guest/wangjia/blindsr/DCLS-SR/experiments/DCLS/001_D2SR_setting2_stage3_x4/models/180000_G.pth
  strict_load: false
  resume_state: ~ #/userHome/guest/wangjia/blindsr/DCLS-SR/experiments/DCLS/001_D2SR_setting2_stage3_x4/training_state/990000.state 


#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_E: !!float 4e-4
  lr_D: !!float 4e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 600000000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  pixel_criterion: l1
  diff_criterion: l1
  kernel_criterion: l1
  pixel_weight: 1.0
  diff_weight: 0.5
  kernel_weight: 1.0

  nl_weight: 0.5 # softmax loss weight
  c_weight: 0.5

  manual_seed: 0
  val_freq: !!float 5e3


#### logger
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
